Cosmetic changes to the top level: fine names READMEs and launch scripts

diff --git a/inspector/scripts/dockerPython b/inspector/scripts/dockerPython
--- a/inspector/scripts/dockerPython
+++ b/inspector/scripts/dockerPython
@@ -1,8 +1,16 @@
 #!/bin/bash
-# doit [build] [shell]
+# dockerPython [build] [shell]
 
 set -e
 DOCKER_TAG=measurementlab/pyrunner
+
+# deduce the user credentials: fail if not exactly one
+shopt -s nullglob
+CREDS=`echo ~/.config/gcloud/legacy_credentials/*`
+if [ `echo "$CREDS" | wc -w` != 1 ]; then
+  echo "Did not find exactly one credential: $CREDS"
+  exit 2
+fi
 
 if [ x$1 = xbuild ]; then
   shift
@@ -10,12 +18,15 @@ if [ x$1 = xbuild ]; then
   mkdir -p tmp
   cp ../plottools/*.py tmp
   sudo docker build . -t $DOCKER_TAG
+  # rm -rf tmp
   echo "Consider: docker push $DOCKER_TAG"
 fi
 
+# show what we are actually doing
+
 set -x
 sudo docker run --net=host \
-  -v  ~/.config/gcloud/legacy_credentials/mattmathis@google.com:/creds \
+  -v  ${CREDS}:/creds \
   -e GOOGLE_APPLICATION_CREDENTIALS=/creds/adc.json \
   --user $UID --group-add users \
   -it $DOCKER_TAG "$*"
