Tools for semi automatic packet capture (pcap) processing on a local workstations.  (#26)
* Prototype view inspector (incomplete)

* Carbon final checkpoint

diff --git a/inspector/testall b/inspector/testall
--- a/inspector/testall
+++ b/inspector/testall
@@ -1,32 +1,116 @@
 #!/bin/bash
 
-# install all views locally
+# default to installing all views locally, no extra chatter
 
-tool=bqsandbox  # Makes views in mlab-sandbox.mm_unified_testing
+export DestID=mlab-sandbox
+export DATASET=mm_unified_testing
+export VERBOSE=''
 
-set -e
+case "x$1" in
+"xpublish")
+  export DestID=mlab-collaboration
+  export DATASET=mm_preproduction
+  ;;
+"xverbose")
+  export VERBOSE='yes'
+  ;;
+"x")
+  ;;
+*)
+  echo "Unknown option $1"
+  exit 2
+  ;;
+esac
+
+
+function mkview {
+  # Write a view to sandbox by default
+  # or to mlab_collaboration to facilitate external testing
+  file=$1
+
+  SourceID=measurement-lab
+#  SourceID=mlab-oti
+  intermediate=${DestID}.${DATASET}
+  viewname=`basename $1 .sql`
+  viewname=`basename $viewname .SQL~`  # SQL generated by others (not really source)
+  TEMP="temp_${viewname}~"
+
+  # Always forbid tabs
+  if fgrep -s $'\t' $file ; then
+    echo "Error: $file contains tabs"
+    exit 2
+  fi
+  cstop="WhatPlatformAnomaly|IsAborted|IsHung| IsRFC1918|NDTprotocol|viewSource|IsValid2019|AS Sources|#|"
+  dlstop="${cstop}upload|c2s|^(  )* [^ ]"
+  ulstop="${cstop}download|s2c|^(  )* [^ ]"
+  # Check things if asked
+  if [ -n "$VERBOSE" ]; then
+    echo
+    echo "$file"
+    if echo "$file" | grep -q download ; then
+      egrep -n -i "$dlstop" "$file"
+      echo "Download banned OK"
+    fi
+    if echo "$file" | grep -q upload ; then
+      egrep -n -i "$ulstop" "$file"
+      echo "Upload banned OK"
+    fi
+  fi
+  egrep -n 'TODO|XXX' "$file" | egrep -v "TODO.*/issues/"
+  echo "TODO OK"
+  # egrep 'AS[ _]*Is[A-Z]' $file
+ 
+  (
+    date=`date`
+    echo "-- Experimental view, subject to frequent breaking changes."
+    echo "-- Manualyl $date $USER"
+    sed -e 's/"/'"'/g" \
+    -e "s;{{\.ProjectID}}\.ndt_intermediate;${intermediate};" \
+    -e "s;{{\.ProjectID}}\.;${SourceID}.;" $file \
+  )  > $TEMP
+  bq rm \
+    --force \
+    --project_id $DestID \
+    $DATASET.$viewname
+
+  echo "Creating $DATASET.$viewname from $file"
+
+  bq mk \
+    --force \
+    --view "`cat $TEMP`" \
+    --use_legacy_sql=false \
+    --project_id=${DestID} \
+    "${DATASET}.${viewname}"
+  if [ $? != 0 ]; then
+    exit 2
+  fi
+
+}
+tool=mkview  # Makes views in mlab-sandbox.mm_unified_testing
+
+
 
 (cd ~/Projects/etl-schema/views
 
-# New ndt_intermediate
-$tool ../views/ndt_intermediate/extended_ndt7_downloads.sql
-$tool ../views/ndt_intermediate/extended_ndt5_downloads.sql
-$tool ../views/ndt_intermediate/extended_web100_downloads.sql
-$tool ../views/ndt_intermediate/extended_ndt7_uploads.sql
-$tool ../views/ndt_intermediate/extended_ndt5_uploads.sql
-$tool ../views/ndt_intermediate/extended_web100_uploads.sql
+ # all uploads
+ $tool ../views/ndt_intermediate/extended_web100_uploads.sql
+ $tool ../views/ndt_intermediate/extended_ndt7_uploads.sql
+ $tool ../views/ndt_intermediate/extended_ndt5_uploads.sql
+ $tool ../views/ndt/unified_uploads.sql
+ sed -e 's/EXCEPT.*//' -e 's/WHERE IsValidBest//' ../views/ndt/unified_uploads.sql > ../views/ndt/unified_uploads_nofilter.SQL~
+ $tool ../views/ndt/unified_uploads_nofilter.SQL~
 
-# New unified 
-$tool ../views/ndt/unified_downloads.sql
-$tool ../views/ndt/unified_uploads.sql
+ # all downloads
+ $tool ../views/ndt_intermediate/extended_ndt7_downloads.sql
+ $tool ../views/ndt_intermediate/extended_ndt5_downloads.sql
+ $tool ../views/ndt_intermediate/extended_web100_downloads.sql
+ # echo "Truncate Build"; date ; exit 0
+ $tool ../views/ndt/unified_downloads.sql
+ sed -e 's/EXCEPT.*//' -e 's/WHERE IsValidBest//' ../views/ndt/unified_downloads.sql > ../views/ndt/unified_downloads_nofilter.SQL~
+ $tool ../views/ndt/unified_downloads_nofilter.SQL~
 
-# New ndt_raw
-$tool ../views/ndt_raw/web100_legacy.sql
-$tool ../views/ndt_raw/ndt5_legacy.sql
-$tool ../views/ndt_raw/traceroute_legacy.sql
-$tool ../views/ndt_raw/tcpinfo_legacy.sql
-$tool ../views/ndt_raw/annotation.sql
-$tool ../views/ndt_raw/ndt7.sql
+ echo -n "Build completed: "
+ date
 )
 
 exit
